name: nagad
description: This is a Flutter package for integrating Nagad's online payment gateway in Flutter app with ease.
version: 0.0.1
authors:
  - Md Sami <mdsami.diu@gmail.com>
 
homepage: https://github.com/mdsami/nagad

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

